services:
  api:
    build: .
    container_name: cobweb_api

    ports:
      - 8000:8000

    volumes:
      - .:/app

    env_file:
      - .env

    command: uv run uvicorn app.main:app --host 0.0.0.0 --reload

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:17

    container_name: cobweb_postgres

    restart: always

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cobweb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cobweb"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine

    container_name: cobweb_redis

    restart: always

    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  worker:
    build: .
    #container_name: cobweb_worker

    command: uv run celery -A app.workers.celery_app worker --loglevel=info

    env_file:
      - .env
    
    volumes:
      - .:/app

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data: