"""add progress column to jobs table

Revision ID: 75143b9c20cf
Revises: a41776681b5d
Create Date: 2026-07-01 09:57:10.470833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75143b9c20cf'
down_revision: Union[str, Sequence[str], None] = 'a41776681b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('progress', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'progress')
    # ### end Alembic commands ###
