"""add error_message to job_urls

Revision ID: a41776681b5d
Revises: 141ffbc22b1a
Create Date: 2026-07-01 09:44:17.250427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41776681b5d'
down_revision: Union[str, Sequence[str], None] = '141ffbc22b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_urls', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_urls', 'error_message')
    # ### end Alembic commands ###
